---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
  namespace: default
  labels: { app: deployment-2 }
spec:
  replicas: 3
  selector:
    matchLabels: { app: deployment-2 }
  template:
    metadata:
      labels: { app: deployment-2 }
    spec:
      containers:
        - name: nginx-1
          image: nginx:latest
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-2-hpa-2lr7
  namespace: default
  labels: { app: deployment-2 }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-2
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
