---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment-2"
  namespace: "default"
  labels:
    app: "deployment-2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "deployment-2"
  template:
    metadata:
      labels:
        app: "deployment-2"
    spec:
      containers:
      - name: "iris-api-sha256-1"
        image: us-central1-docker.pkg.dev/helical-castle-461412-n2/my-repo/iris-api:latest

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "deployment-2-hpa-v74t"
  namespace: "default"
  labels:
    app: "deployment-2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "deployment-2"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "deployment-2-service"
  namespace: "default"
  labels:
    app: "deployment-2"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: "deployment-2"
  type: "LoadBalancer"
  loadBalancerIP: ""
